In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df= pd.read_csv('train.txt', sep = ';',header=None, names=['text','Emotions'])

In [5]:
df.head()

                                                text Emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [6]:
df.isnull().sum()

text        0
Emotions    0
dtype: int64

In [7]:
df['Emotions'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [ ]:
#  Convert emotion labels (text) into numbers (Label Encoding)
# ML models cannot understand text, so we convert categories → numerical values

# Step 1: Get unique emotion labels
unique_emotions=df['Emotions'].unique()


# Step 2: Create mapping dictionary (emotion → number)
emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i+=1
# Example mapping:
# {'happy': 0, 'sad': 1, 'angry': 2}

# Step 3: Replace text labels with numbers in dataframe
df['Emotions']=df['Emotions'].map(emotion_numbers)

In [9]:
unique_emotions

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [13]:
df

                                                    text  Emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]