In [59]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [84]:
df= pd.read_csv('train.txt', sep = ';',header=None, names=['text','Emotions'])

In [85]:
df.head()

                                                text Emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [86]:
df.isnull().sum()

text        0
Emotions    0
dtype: int64

In [87]:
df['Emotions'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [88]:
#  Convert emotion labels (text) into numbers (Label Encoding)
# ML models cannot understand text, so we convert categories → numerical values

# Step 1: Get unique emotion labels
unique_emotions=df['Emotions'].unique()


# Step 2: Create mapping dictionary (emotion → number)
emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i+=1
# Example mapping:
# {'happy': 0, 'sad': 1, 'angry': 2}

# Step 3: Replace text labels with numbers in dataframe
df['Emotions']=df['Emotions'].map(emotion_numbers)

In [89]:
unique_emotions

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [90]:
df.head()

                                                text  Emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

In [91]:
# lets clean Text now
# lower case 
df['text']= df['text'].apply(lambda x: x.lower())

In [92]:

# removing punctuation

import string 

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))
# apply on text column
df['text']=df['text'].apply(remove_punc)

In [93]:
# removing numbers 
def remove_numb(txt):
    new =""
    for i in txt:
        if not i.isdigit():
            new= new + i 
    return new 
# apply on text col for removing num 
df['text']=df['text'].apply(remove_numb)

In [94]:
# removing emojis 

def remove_emojis(txt):
    new =""
    for i in txt:
        if i.isascii():
            new= new + i 
    return new 
# removing emoji 
# apply on text col for removing num 

df['text']=df['text'].apply(remove_emojis)

In [95]:
df.head()

                                                text  Emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

In [96]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [97]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [98]:
# stopwords
stop_words = set(stopwords.words('english'))
# stop_words

In [99]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [100]:
# now lets do tokenization for removing stop words 

def remove_stopwords(txt):
  words = txt.split() #tokenization
  
  cleaned = []
  for i in words:
    if not i in stop_words: # remove stop words 
      cleaned.append(i)

  return ' '.join(cleaned) # join back to sentence

  # apply
df['text'] = df['text'].apply(remove_stopwords)

In [101]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'